/** Localized labels shared by the Footer editor and its customer renderer. */
export function footerCopy(locale: string) {
  return copy[locale === "fr" || locale === "he" ? locale : "en"];
}
const copy = {
  en: {
    branding: "Footer branding",
    showBranding: "Show Foody branding",
    brandingHelp:
      "This signature is shared across all pages, independently of the footer.",
    style: "Section style",
    layout: "Layout",
    columns: "Two columns",
    centered: "Centered",
    background: "Background",
    theme: "Your selected color style",
    color: "Custom color",
    gradient: "Gradient",
    image: "Image",
    logo: "Logo",
    type: "Type",
    text: "Text",
    size: "Size",
    small: "Small",
    medium: "Medium",
    large: "Large",
    navigation: "Navigation",
    sameHeader: "Same as header navigation",
    homeHelp: "Your logo links to your homepage.",
    subscriptionTitle: "Subscription title",
    subscription: "Subscription",
    placeholder: "Input placeholder",
    button: "Button label",
    formName: "Form name",
    confirmation: "Confirmation message",
    filled: "Filled",
    outline: "Outline",
    social: "Social icons",
    socialColor: "Icon color",
    socialMedia: "Social media",
    main: "Main color",
    light: "Light text",
    dark: "Dark text",
    external: "External links",
    addLink: "Add link",
    label: "Label",
    url: "Destination",
    remove: "Remove",
    payments: "Payment methods",
    paymentHelp: "Show only the card networks accepted by your restaurant.",
    copyright: "Copyright text",
    contact: "Restaurant details",
    stayLoop: "Stay in the Loop",
    email: "Email",
    signup: "Sign Up",
    thanks: "Thank you for subscribing.",
    consent:
      "By subscribing, you agree to receive updates from this restaurant.",
  },
  fr: {
    branding: "Signature du pied de page",
    showBranding: "Afficher la signature Foody",
    brandingHelp:
      "Cette signature est partagée entre toutes les pages, indépendamment du pied de page.",
    style: "Style de la section",
    layout: "Disposition",
    columns: "Deux colonnes",
    centered: "Centré",
    background: "Arrière-plan",
    theme: "Votre style de couleurs sélectionné",
    color: "Couleur personnalisée",
    gradient: "Dégradé",
    image: "Image",
    logo: "Logo",
    type: "Type",
    text: "Texte",
    size: "Taille",
    small: "Petit",
    medium: "Moyen",
    large: "Grand",
    navigation: "Navigation",
    sameHeader: "Identique à la navigation de l’en-tête",
    homeHelp: "Votre logo renvoie vers votre page d’accueil.",
    subscriptionTitle: "Titre de l’inscription",
    subscription: "Inscription",
    placeholder: "Texte indicatif du champ",
    button: "Libellé du bouton",
    formName: "Nom du formulaire",
    confirmation: "Message de confirmation",
    filled: "Plein",
    outline: "Contour",
    social: "Icônes des réseaux sociaux",
    socialColor: "Couleur des icônes",
    socialMedia: "Couleurs des réseaux sociaux",
    main: "Couleur principale",
    light: "Texte clair",
    dark: "Texte sombre",
    external: "Liens externes",
    addLink: "Ajouter un lien",
    label: "Libellé",
    url: "Destination",
    remove: "Supprimer",
    payments: "Moyens de paiement",
    paymentHelp:
      "Affichez uniquement les réseaux de cartes acceptés par votre restaurant.",
    copyright: "Texte de copyright",
    contact: "Coordonnées du restaurant",
    stayLoop: "Gardons le contact",
    email: "E-mail",
    signup: "S’inscrire",
    thanks: "Merci pour votre inscription.",
    consent:
      "En vous inscrivant, vous acceptez de recevoir les actualités de ce restaurant.",
  },
  he: {
    branding: "מיתוג כותרת תחתונה",
    showBranding: "הצגת מיתוג Foody",
    brandingHelp: "המיתוג משותף לכל הדפים בנפרד מהכותרת התחתונה.",
    style: "סגנון המקטע",
    layout: "פריסה",
    columns: "שתי עמודות",
    centered: "ממורכז",
    background: "רקע",
    theme: "סגנון הצבע שנבחר",
    color: "צבע מותאם",
    gradient: "מעבר צבע",
    image: "תמונה",
    logo: "לוגו",
    type: "סוג",
    text: "טקסט",
    size: "גודל",
    small: "קטן",
    medium: "בינוני",
    large: "גדול",
    navigation: "ניווט",
    sameHeader: "זהה לניווט בכותרת העליונה",
    homeHelp: "הלוגו מקשר לדף הבית.",
    subscriptionTitle: "כותרת הרשמה",
    subscription: "הרשמה",
    placeholder: "טקסט מציין מקום",
    button: "תווית הכפתור",
    formName: "שם הטופס",
    confirmation: "הודעת אישור",
    filled: "מלא",
    outline: "קו מתאר",
    social: "סמלי רשתות חברתיות",
    socialColor: "צבע סמלים",
    socialMedia: "צבעי הרשתות",
    main: "צבע ראשי",
    light: "טקסט בהיר",
    dark: "טקסט כהה",
    external: "קישורים חיצוניים",
    addLink: "הוספת קישור",
    label: "תווית",
    url: "יעד",
    remove: "הסרה",
    payments: "אמצעי תשלום",
    paymentHelp: "הציגו רק רשתות כרטיסים שהמסעדה מקבלת.",
    copyright: "טקסט זכויות יוצרים",
    contact: "פרטי המסעדה",
    stayLoop: "נשארים בקשר",
    email: "אימייל",
    signup: "הרשמה",
    thanks: "תודה שנרשמתם.",
    consent: "בהרשמה אתם מסכימים לקבל עדכונים מהמסעדה.",
  },
};
